In [116]:
from numpy.random import seed
seed(1)
# Dependencies
import numpy as np
import pandas as pd
import tensorflow
tensorflow.keras.__version__

'2.2.4-tf'

In [117]:
target = pd.read_csv('target.csv')
target.head()

,Date,Target,binary_target,target_1,binary_1,target_3,binary_3,target_5,binary_5
0,10/1/2001,0.0,0,0.0,0,0.0,0,0.0,0
1,10/2/2001,0.0,0,0.0,0,0.1,1,0.0,0
2,10/3/2001,0.0,0,0.0,0,0.0,0,0.0,0
3,10/4/2001,0.0,0,0.1,1,0.0,0,0.3,1
4,10/5/2001,0.1,1,0.0,0,0.0,0,0.0,0

In [118]:
snotel = pd.read_csv('snotel.csv')
snotel.head()

,Date,Agua Canyon (907) Precipitation Increment - Snow-adj (in),Albro Lake (916) Precipitation Increment - Snow-adj (in),Aneroid Lake #2 (302) Precipitation Increment - Snow-adj (in),Apishapa (303) Precipitation Increment - Snow-adj (in),Arapaho Ridge (1030) Precipitation Increment - Snow-adj (in),Atlanta Summit (306) Precipitation Increment - Snow-adj (in),Baker Butte (308) Precipitation Increment - Snow-adj (in),Baker Butte Smt (1140) Precipitation Increment - Snow-adj (in),Bald Mtn. (309) Precipitation Increment - Snow-adj (in),...,Willow Park (870) Precipitation Increment - Snow-adj (in),Wilson Creek (871) Precipitation Increment - Snow-adj (in),Windy Peak (872) Precipitation Increment - Snow-adj (in),Wolf Creek Peak (1164) Precipitation Increment - Snow-adj (in),Wolf Creek Summit (874) Precipitation Increment - Snow-adj (in),Wolverine (875) Precipitation Increment - Snow-adj (in),Wrigley Creek (1228) Precipitation Increment - Snow-adj (in),Yankee Reservoir (1197) Precipitation Increment - Snow-adj (in),Younts Peak (878) Precipitation Increment - Snow-adj (in),Zirkel (1033) Precipitation Increment - Snow-adj (in)
0,10/1/2001,0.0,0.0,0.1,0.0,NaN,0.0,0.0,NaN,0.0,...,0.0,0.0,0.1,NaN,0.0,0.0,NaN,NaN,0.0,NaN
1,10/2/2001,0.0,0.0,0.1,0.0,NaN,0.0,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.1,NaN
2,10/3/2001,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN
3,10/4/2001,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,...,0.0,0.0,0.3,NaN,0.0,0.3,NaN,NaN,0.0,NaN
4,10/5/2001,0.1,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.2,...,0.0,0.0,0.3,NaN,0.0,0.0,NaN,NaN,0.0,NaN

In [119]:
df=pd.merge(target,snotel, on='Date', how = 'left')

In [120]:
df.corr()[['target_3']].sort_values('target_3')

                                                    target_3
Lookout Mountain (595) Precipitation Increment ... -0.014590
Mcknight Cabin (1048) Precipitation Increment -... -0.005641
Signal Peak (755) Precipitation Increment - Sno...  0.002730
Sucker Creek (798) Precipitation Increment - Sn...  0.002896
Frisco Divide (486) Precipitation Increment - S...  0.004185
...                                                      ...
binary_1                                            0.140067
binary_5                                            0.164270
Wolf Creek Peak (1164) Precipitation Increment ...  0.181586
binary_3                                            0.626544
target_3                                            1.000000

[512 rows x 1 columns]

In [121]:
y = df['binary_3']

In [122]:
X = df.iloc[:,5:]

X.fillna(df.mean(), inplace=True)

In [123]:
X

,target_3,binary_3,target_5,binary_5,Agua Canyon (907) Precipitation Increment - Snow-adj (in),Albro Lake (916) Precipitation Increment - Snow-adj (in),Aneroid Lake #2 (302) Precipitation Increment - Snow-adj (in),Apishapa (303) Precipitation Increment - Snow-adj (in),Arapaho Ridge (1030) Precipitation Increment - Snow-adj (in),Atlanta Summit (306) Precipitation Increment - Snow-adj (in),...,Willow Park (870) Precipitation Increment - Snow-adj (in),Wilson Creek (871) Precipitation Increment - Snow-adj (in),Windy Peak (872) Precipitation Increment - Snow-adj (in),Wolf Creek Peak (1164) Precipitation Increment - Snow-adj (in),Wolf Creek Summit (874) Precipitation Increment - Snow-adj (in),Wolverine (875) Precipitation Increment - Snow-adj (in),Wrigley Creek (1228) Precipitation Increment - Snow-adj (in),Yankee Reservoir (1197) Precipitation Increment - Snow-adj (in),Younts Peak (878) Precipitation Increment - Snow-adj (in),Zirkel (1033) Precipitation Increment - Snow-adj (in)
0,0.0,0,0.0,0,0.0,0.0,0.10000,0.0,0.116989,0.0,...,0.000000,0.0,0.1,0.086022,0.0,0.0,0.06582,0.069043,0.000000,0.150372
1,0.1,1,0.0,0,0.0,0.0,0.10000,0.0,0.116989,0.0,...,0.000000,0.0,0.0,0.086022,0.0,0.0,0.06582,0.069043,0.100000,0.150372
2,0.0,0,0.0,0,0.0,0.0,0.00000,0.0,0.116989,0.0,...,0.000000,0.0,0.0,0.086022,0.0,0.0,0.06582,0.069043,0.000000,0.150372
3,0.0,0,0.3,1,0.0,0.0,0.00000,0.0,0.116989,0.0,...,0.000000,0.0,0.3,0.086022,0.0,0.3,0.06582,0.069043,0.000000,0.150372
4,0.0,0,0.0,0,0.1,0.0,0.00000,0.0,0.116989,0.0,...,0.000000,0.0,0.3,0.086022,0.0,0.0,0.06582,0.069043,0.000000,0.150372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7088,0.2,1,0.0,0,0.0,0.3,0.14407,0.0,0.200000,0.7,...,0.100000,0.3,0.0,0.600000,0.0,0.2,0.20000,0.000000,0.300000,0.400000
7089,0.0,0,0.0,0,0.0,0.1,0.14407,0.0,0.100000,0.2,...,0.100000,0.3,0.1,0.100000,0.0,0.0,0.00000,0.000000,0.000000,0.300000
7090,0.0,0,0.0,0,0.0,0.0,0.14407,0.1,0.000000,0.1,...,0.100000,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
7091,0.0,0,0.0,0,0.0,0.1,0.14407,0.3,0.100000,0.0,...,0.200000,0.1,0.2,0.100000,0.0,0.1,0.00000,0.300000,0.300000,0.100000
7092,0.0,0,0.0,0,0.0,0.0,0.14407,0.1,0.100000,0.1,...,0.118923,0.1,0.1,0.000000,0.1,0.0,0.10000,0.000000,0.094062,0.100000

In [124]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [125]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train)

In [126]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [127]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [128]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [129]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [130]:
from sklearn.linear_model import LinearRegression
# instantiate the regressor class
regressor = LinearRegression()

# fit the build the model by fitting the regressor to the training data
regressor.fit(X_train, y_train)

# make a prediction set using the test set
prediction = regressor.predict(X_test)

# Evaluate the prediction accuracy of the model
from sklearn.metrics import mean_absolute_error, median_absolute_error
print("The Explained Variance: %.2f" % regressor.score(X_test, y_test))
print("The Mean Absolute Error: %.2f degrees celsius" % mean_absolute_error(y_test, prediction))
print("The Median Absolute Error: %.2f degrees celsius" % median_absolute_error(y_test, prediction))

The Explained Variance: 1.00
The Mean Absolute Error: 0.00 degrees celsius
The Median Absolute Error: 0.00 degrees celsius