In [57]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import os

In [58]:
df = pd.read_csv('fc1.csv')
df.head()

,Date,Year,DOY,Solar,Wind_speed,Wind_dir,gust,temp,rh,precip,...,Webber Springs,Webster Flat,Whiskey Ck,Whiskey Park,White Elephant,White Mill,Widtsoe #3,Willow Creek,Willow Creek Pass,Windy Peak
0,10/1/2001,2001,274,383.0,2.00,120.0,19.0,47.8,50.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1
1,10/2/2001,2001,275,478.0,3.83,124.0,27.0,49.0,40.0,0.0,...,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10/3/2001,2001,276,482.0,3.35,60.0,22.0,47.3,37.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10/4/2001,2001,277,483.0,5.12,333.0,27.0,47.2,32.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3
4,10/5/2001,2001,278,482.0,3.46,3.0,24.0,39.2,38.0,0.0,...,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3

In [59]:


y = df["binary_1"]
target_names = ["0", "1"]

In [60]:


X = df.drop(['binary_1','Date'], axis = 1 )

X.fillna(df.mean(), inplace=True)

In [61]:
X

,Year,DOY,Solar,Wind_speed,Wind_dir,gust,temp,rh,precip,Agua Canyon,...,Webber Springs,Webster Flat,Whiskey Ck,Whiskey Park,White Elephant,White Mill,Widtsoe #3,Willow Creek,Willow Creek Pass,Windy Peak
0,2001,274,383.0,2.00,120.0,19.0,47.8,50.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1
1,2001,275,478.0,3.83,124.0,27.0,49.0,40.0,0.00,0.0,...,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2001,276,482.0,3.35,60.0,22.0,47.3,37.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2001,277,483.0,5.12,333.0,27.0,47.2,32.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3
4,2001,278,482.0,3.46,3.0,24.0,39.2,38.0,0.00,0.1,...,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7088,2021,57,431.0,7.21,287.0,53.0,19.8,42.0,0.00,0.0,...,0.5,0.0,0.0,0.6,0.7,0.2,0.0,0.6,0.0,0.0
7089,2021,58,210.0,4.12,346.0,24.0,11.8,70.0,0.00,0.0,...,0.2,0.0,0.0,0.3,0.1,0.0,0.0,0.5,0.3,0.1
7090,2021,59,493.0,3.08,59.0,15.0,5.8,56.0,0.01,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.1,0.0,0.0
7091,2021,60,510.0,2.67,148.0,12.0,16.4,54.0,0.00,0.0,...,0.1,0.3,0.3,0.1,0.0,0.2,0.1,0.1,0.1,0.2
7092,2021,61,518.0,3.00,54.0,14.0,25.1,47.0,0.00,0.0,...,0.1,0.1,0.0,0.1,0.0,0.0,0.0,0.1,0.1,0.1

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [63]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='rbf')
model.fit(X_train, y_train)

SVC()

In [64]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 0.663

In [65]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train)

In [66]:
# Transform the training and testing data using the X_scaler and y_scaler models

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [67]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='rbf')
model.fit(X_train, y_train)

SVC()

In [68]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 0.663

In [69]:
predictions=model.predict(X)

In [71]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)